//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456
        ///password
        ///12345678
        ///qwerty
        ///123456789
        ///12345
        ///1234
        ///111111
        ///1234567
        ///dragon
        ///123123
        ///baseball
        ///abc123
        ///football
        ///monkey
        ///letmein
        ///696969
        ///shadow
        ///master
        ///666666
        ///qwertyuiop
        ///123321
        ///mustang
        ///1234567890
        ///michael
        ///654321
        ///pussy
        ///superman
        ///1qaz2wsx
        ///7777777
        ///fuckyou
        ///121212
        ///000000
        ///qazwsx
        ///123qwe
        ///killer
        ///trustno1
        ///jordan
        ///jennifer
        ///zxcvbnm
        ///asdfgh
        ///hunter
        ///buster
        ///soccer
        ///harley
        ///batman
        ///andrew
        ///tigger
        ///sunshine
        ///iloveyou
        ///fuckme
        ///2000
        ///charlie
        ///robert
        ///thomas
        ///hockey
        ///ranger
        ///daniel
        ///starwars
        ///klaster
        ///112233
        ///george
        ///asshole
        ///computer
        ///michelle
        ///jessica
        ///pepper
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _100kCommonPasswords {
            get {
                return ResourceManager.GetString("100kCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root
        ///admin
        ///1234
        ///user
        ///Administrator
        ///administrador
        ///usuario2
        ///usuario
        ///user4
        ///user3
        ///user2
        ///user1
        ///12345
        ///123456
        ///daemon
        ///bin
        ///sys
        ///sync
        ///games
        ///man
        ///lp
        ///mail
        ///news
        ///uucp
        ///proxy
        ///www-data
        ///backup
        ///nobody
        ///a
        ///welcome123
        ///welcome
        ///webmaster
        ///webadmin
        ///vision
        ///valentin
        ///uuidd
        ///uploader
        ///unknown
        ///ubuntu
        ///ubnt
        ///trustno1
        ///toor
        ///tomcat
        ///thomas
        ///testtest
        ///test123
        ///test
        ///temptemp
        ///temporary
        ///temporal
        ///temp123
        ///tang
        ///systemadministrator
        ///systemadmin
        ///system32
        ///system
        ///sysadmin
        ///sys
        ///sybase
        ///support
        ///supervisor
        ///superuser
        ///supernic.cn
        ///superadmin
        ///super
        ///sunshine
        ///sudo
        ///student
        ///st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1kCommonUsernames {
            get {
                return ResourceManager.GetString("1kCommonUsernames", resourceCulture);
            }
        }
    }
}
